runners:
  - name: "cirun-gcp-amd64"
    cloud: "gcp"
    machine_image: "sealos-dev:cirun-action-podman-500g"  # YOUR-PROJECT-NAME:MACHINE-IMAGE-NAME
    instance_type:
      - "c3-highmem-4"
      - "c3-highcpu-8"
      - "e2-custom-8-32768"
    labels:
      - "cirun-gcp-amd64"
    region:
      - "us-central1-a"
      - "us-central1-b"
      - "us-central1-c"
      - "us-central1-f"
      - "us-east1-b"
      - "us-east1-c"
      - "us-east1-d"
      - "us-east4-a"
      - "us-east4-b"
      - "us-east4-c"
      - "us-west1-a"
      - "us-west1-b"
      - "us-west1-c"
