runners:
  - name: "cirun-gcp-amd64"
    cloud: "gcp"
    machine_image: "sealos-dev:cirun-action-podman-500g"  # YOUR-PROJECT-NAME:MACHINE-IMAGE-NAME
    instance_type:
      - "c3-highmem-4"
      - "c3-highcpu-8"
      - "e2-custom-8-32768"
    labels:
      - "cirun-gcp-amd64"
    region:
      - "asia-east1-a"
      - "asia-east1-b"
      - "asia-east1-c"
      - "asia-east2-a"
      - "asia-east2-b"
      - "asia-east2-c"
      - "us-west1-b"
      - "us-west1-a"
      - "us-west1-c"
      - "us-west2-b"
      - "us-west2-a"
      - "us-west2-c"
